SITES_TO_VISIT = {'https://www.nytimes.com': {'pic': 'nytimes.png', 'name': 'New York Times', 'route_name': 'NYT'},
				  'https://www.foxnews.com': {'pic': 'foxnews.png', 'name': 'Fox News', 'route_name': 'FoxNews'}, 
				  'https://www.motherjones.com': {'pic': 'motherjones.png', 'name': 'Mother Jones', 'route_name': 'MotherJones'}, 
				  'http://www.buzzfeednews.com': {'pic': 'buzzfeednews.png', 'name': 'Buzz Feed News', 'route_name': 'BuzzFeed'}, 
				  'http://www.washingtonpost.com': {'pic': 'washingtonpost.png', 'name': 'Washington Post', 'route_name': 'WashingtonPost'}, 
				  'https://www.reuters.com': {'pic': 'reuters.png', 'name': 'Reuters', 'route_name': 'Reuters'}, 
				  'https://www.axios.com': {'pic': 'axios.png', 'name': 'Axios', 'route_name': 'Axios'}, 
				  'http://www.politico.com': {'pic': 'politico.png', 'name': 'Politico', 'route_name': 'Politico'}, 
				  'https://www.wsj.com': {'pic': 'wsj.png', 'name': 'The Wall Street Journal', 'route_name': 'WSJ'}, 
				  'http://www.washingtontimes.com': {'pic': 'washingtontimes.png', 'name': 'The Washington Times', 'route_name': 'WashingtonTimes'},
				  'https://www.nypost.com': {'pic': 'nypost.png', 'name': 'New York Post', 'route_name': 'NYP'},
				  'https://www.nationalreview.com': {'pic': 'nationalreview.png', 'name': 'The National Review', 'route_name': 'NationalReview'},
				  'https://www.infowars.com': {'pic': 'infowars.png', 'name': 'Info Wars', 'route_name': 'InfoWars'},
				  'http://www.breitbart.com': {'pic': 'breitbart.png', 'name': 'Breitbart', 'route_name': 'Breitbart'}
				  }
